
server.port: 8888

spring:
  main.banner-mode: 'OFF'
  h2:
    console:
      enabled: true
      path: /h2

management.endpoints.web.exposure.include:
  - health
  - heapdump
  - env
  - metrics

logging.level:
  org.springframework: INFO
  reservation.bus: INFO
